SELECT ranked.FOOD_TYPE, ranked.REST_ID, ranked.REST_NAME, ranked.FAVORITES
FROM (
    SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES,
           ROW_NUMBER() OVER (PARTITION BY FOOD_TYPE ORDER BY FAVORITES DESC) AS rn
    FROM REST_INFO
) ranked
WHERE ranked.rn = 1
ORDER BY FOOD_TYPE DESC;